# Generated by Django 5.0.3 on 2024-04-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_product_id_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
