# Generated by Django 5.0.3 on 2024-04-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_product_id_alter_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
