# Generated by Django 5.0.3 on 2024-04-06 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_product_userid_alter_productimages_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productID',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimages',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
