# Generated by Django 5.0.3 on 2024-04-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_remove_product_productid_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='productID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
