# Generated by Django 5.0.3 on 2024-04-06 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_alter_product_productid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productID',
            new_name='productid',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='productID',
            new_name='productid',
        ),
    ]
