# Generated by Django 5.0.3 on 2024-04-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_rename_productid_product_productid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='productid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productid',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
